version: '3.8'
services:
  app:
    container_name: test-jenkins
    build:
      dockerfile: Dockerfile
    image: test-jenkins:latest
    ports:
      - "8083:8080"
    restart: on-failure
    network_mode: bridge